### ISSUE TITLE
[Question] how is this different from django-fsm and can I use this in conjunction with it?

### ISSUE THREAD

**Issue by simkimsia** [rsinger86/django-lifecycle#56]
i have been using django-lifecycle for a while to merely store the status. But I am realizing that I am building towards something like a Finite State machine. 

So not sure if this library and https://github.com/viewflow/django-fsm overlap or I can use them in conjunction

I do find the idea of eschewing Signals for Hooks in this library for greater readability to be appealing.

**Comment by rsinger86** [comment]
That looks like a useful project. I did not know about it. I have not gone deep, but a key difference appears to be that django-fsm (as the name suggests) is more about *controlling* transitions between states. Meanwhile, django-lifecycle is more about *monitoring* state transitions and triggering actions based on them.

If your application need tight, declarative control over how model fields can be changed, django-fsm could be a good choice. If your application needs to trigger other actions when model state changes, django-lifecycle could be a good choice. 

I have not tested them in conjunction, but I'm optimistic that they can be used together because django-fsm looks like it uses specialized fields (django-lifecycle uses a model or model mixin).

**Comment by simkimsia** [comment]
Thanks for reply, @rsinger86 

I think I will use them together

The FSM project apparently uses signals to trigger the transition between the model states.

Whereas your lifecycle project prefers hooks for triggering changes.

I was wondering if you think it's worth it to fork the FSM project that use lifecycle hooks to accomplish the same thing?

**Comment by rsinger86** [comment]
Your idea is to customize the FSM project to trigger changes with lifecycle hooks instead of signals?

**Comment by simkimsia** [comment]
Yes

Of course I'm not sure if it's even worth it

Just spitballing and like to hear your thoughts

**Comment by rsinger86** [comment]
I'm not what the additional benefit would be of using lifecycle hooks instead of signals to trigger changes in FSM. 

I do see some interesting overlap between the projects, so thank you for bringing this. In my own projects, I prefer to do validation in serializers, but I can see the appeal of defining allowed transitions on the model class.

**Comment by simkimsia** [comment]
Just an update, 

currently, I am using FSMField in https://github.com/viewflow/django-fsm to 

1. define a `state` field
2. define what transitions are allowed on that `state` field at the model class level
3. define side effects of the transition not easily handled by lifecycle hook methods for e.g. I want to change a field based on current request user. I can create a transition that takes in an extra parameter but the hook methods seem to only allow interaction with the current instance attributes and values.

Then I use lifecycle hook methods to define the side effects before/after the `state` field has been changed and other side effects that have nothing to do with state transitions.

AM very happy with this setup.

Closing this question
